### ISSUE TITLE
Add NAV Objects to repo

### ISSUE THREAD

**Issue by mitrov** [vjekob/NAV-Assembly-Resolver#1]
Hi Vjeko

I see that you have updated the the c# code for the Assembly Resolver.
Could you also add the (updated?) NAV Objects to this repo? That would be great.

Best regards
Džoka Mitrov

**Comment by vjekob** [comment]
Hi Džoka,

Thanks for finding this repo out. How in the earth did you do that? :)

Anyway - I will publish this - I've been working on this thing intensively over the past couple of weeks, so there will be stuff here, no worries.

And thanks for caring, I really appreciate it!

Cheers,

Vjeko
